version: "2"

services:
  portainer:
    image: portainer/portainer-ce:2.5.1
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    networks:
      - portainernet
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=9000
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data

networks:
  portainernet:
    driver: bridge
